image: java:8-jdk

stages:
  - build
  - package
  - publish

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx512m"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  before_script:
    - apt update && apt install -y make
  script:
    - make installDist

deb:build:
  stage: package
  image: registry.git.callpipe.com/finn/debian-repo-builder:latest
  before_script:
    - export VERSION=$(./version.sh)
    - echo "Building signald version $VERSION"
  tags:
    - package-signer
  script:
    - gbp dch --ignore-branch --debian-tag="%(version)s" --git-author --new-version="$VERSION"
    - cat debian/changelog
    - dpkg-buildpackage --sign-key=D89FFB45291229A410A1430A659475081F665F29 -b
    - cp -rv ../signald_${VERSION}* .
  artifacts:
    paths:
      - "signald_*"

deb:publish:
  stage: publish
  image: registry.git.callpipe.com/finn/debian-repo-builder:latest
  tags:
    - package-signer
  before_script:
    - mc config host add minio "${MINIO_URL}" "${MINIO_ACCESS_KEY}" "${MINIO_SECRET_KEY}"
    - export SUITE=$(get-suite)
    - export VERSION=$(./version.sh)
    - mkdir -p public/dists/${SUITE}/
    - mc cp -r -q "minio/updates.signald.org/dists/${SUITE}/" public/ || true
    - cd public
  script:
    - release-deb ../ D89FFB45291229A410A1430A659475081F665F29
    - gpg --homedir /opt/signing-keys/.gnupg --export --armor D89FFB45291229A410A1430A659475081F665F29 > apt-signing-key.asc
    - for f in "dist/${SUITE}/main/binary-amd64/${VERSION}_all.deb" $(find -type f | grep -v -E "\.deb$"); do mc cp -r -q "$f" "minio/updates.signald.org/$f"; done
  dependencies:
    - deb:build
