image: java:8-jdk

stages:
  - check for updates
  - build
  - test
  - publish
  - cleanup

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx512m"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  before_script:
    - apt-get update && apt-get install -y make
  script:
    - make installDist
  artifacts:
    paths:
      - build/

deb:build:
  stage: build
  image: registry.git.callpipe.com/finn/debian-repo-builder:latest
  allow_failure: true  # TODO: Disallow failure when the same build.gradle file can be used to run the tests *and* build the deb - currently the config to run the tests requires gradle 4.6+ and Debian Sid only has gradle 4.4
  before_script:
    - export VERSION=$(./version.sh)
    - echo "Building signald version $VERSION"
  script:
    - gbp dch --ignore-branch --debian-tag="%(version)s" --git-author --new-version="$VERSION"
    - cat debian/changelog
    - dpkg-buildpackage -b
    - cp -rv ../signald_${VERSION}* .
  artifacts:
    paths:
      - "signald_*"

deb:publish:
  stage: publish
  image: registry.git.callpipe.com/finn/debian-repo-builder:latest
  tags:
    - package-signer
  before_script:
    - mc config host add minio "${MINIO_URL}" "${MINIO_ACCESS_KEY}" "${MINIO_SECRET_KEY}"
    - export SUITE=$(get-suite)
    - export VERSION=$(./version.sh)
    - mkdir -p public/dists/${SUITE}/
    - mc cp -r -q "minio/updates.signald.org/dists/${SUITE}/" public/ || true
  script:
    - gpg --detach-sign signald_${VERSION}*.deb
    - cd public
    - release-deb ../ "${SIGNING_KEY}"
    - gpg --export --armor "${SIGNING_KEY}" > apt-signing-key.asc
    - for f in apt-signing-key.asc dists/${SUITE}/main/binary-amd64/signald_${VERSION}* $(find dists/ -type f | grep -v -E "\.deb$"); do mc cp -q "$f" "minio/updates.signald.org/$f"; done
  artifacts:
    paths:
      - "signald_*.sig"
  dependencies:
    - deb:build

test:integration:
  stage: test
  before_script:
    - cp tools/log4j2.xml src/main/resources/log4j2.xml
    - ./gradlew installDist  # must be run before keytool to download the BouncyCastle jar
    - keytool -storetype BKS -provider org.bouncycastle.jce.provider.BouncyCastleProvider -providerpath build/install/signald/lib/bcprov-jdk15on-1.60.jar -keystore src/main/resources/io/finn/signald/whisper.store -storepass whisper -import -noprompt -alias isrg-root-x1 -file tools/letsencrypt-x3.pem
  script:
    - ./gradlew clean integrationTest --info
  variables:
    SIGNAL_URL: $SIGNAL_TEST_SERVER
  artifacts:
    reports:
      junit: build/test-results/integrationTest/TEST-io.finn.signald.TestRequest.xml
  dependencies:
    - build

deb:cleanup:
  stage: cleanup
  image: registry.git.callpipe.com/finn/debian-repo-builder:latest
  before_script:
    - mc config host add minio "${MINIO_URL}" "${MINIO_ACCESS_KEY}" "${MINIO_SECRET_KEY}"
  script:
    - repo-cron minio/updates.signald.org

checkupdates:gradle:
  stage: check for updates
  only:
    - schedules
  before_script:
    - apt-get update && apt-get install -y jq
    - mkdir -p ~/.ssh
    - echo "$GIT_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
    - echo "$GITLAB_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - git config --global user.email "upgrade-robot@signald.org"
    - git config --global user.name "Upgrade Robot"
    - git remote set-url origin git@git.callpipe.com:finn/signald.git
  script:
    - ./gradlew checkLibVersions | grep UPGRADE | cut -c 9- | tools/check-gradle-updates.sh
