image: java:8-jdk

stages:
  - build
  - package

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - make installDist
  after_script:
    - cp -r build/install/signald .
  artifacts:
    paths:
      - signald
    expire_in: 1 week

deb:
  stage: package
  script:
    - make deb
    - mv build/distributions/*.deb .
  only:
    - tags
  artifacts:
    paths:
      - "*.deb"
